/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectotienda;



import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mike
 */
public class Access extends javax.swing.JFrame {

    /**
     * Creates new form frame
     */
    public Access() throws ClassNotFoundException, SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
       noversino();
          combo.setVisible(false);
         noveropcionesdeadmin();
         noverincorrecto();
         noverbotones();
        conexion();
        addvendedores();
    }
    
    
    void verbotones(){
        labelvendedor.setVisible(true);
        accedervendedor.setVisible(true);
        vendedorpassword.setVisible(true);
    }
    void noverbotones(){
        labelvendedor.setVisible(false);
        accedervendedor.setVisible(false);
        vendedorpassword.setVisible(false);
    }
    
    void addvendedores() throws SQLException, ClassNotFoundException{
     conexion();
      Statement s=con.createStatement();
            ResultSet r=s.executeQuery("SELECT * FROM credenciales where credencial = 'Vendedor' ");
            while(r.next()){
               u=r.getString("usuario");
             c=r.getString("contraseña");
             combo.addItem(u);
            }  
    }
  
Connection con;
    public void conexion() throws ClassNotFoundException, SQLException{
        Class.forName("com.mysql.jdbc.Driver");
        con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/basetienda","root","");
        System.out.println("Conexion exitosa");
        comprobarcuentas();
}
    
    

    public void insertar() throws SQLException, ClassNotFoundException{
   
}
    public void comprobarcuentas() throws SQLException{
        int contador=0;
       String valores="";
       Statement s=con.createStatement();
       ResultSet r=s.executeQuery("SELECT * FROM productos");
       while(r.next()){
           contador++;
       }
       if(contador>0){
           System.out.println("Hay regisros");
           si.setVisible(false);
         no.setVisible(false);
          labe.setText("BUENOS DIAS ☺");
       }else{
           System.out.println("No hay registros");
      labe.setText("BIENVENDO ¿DESEA AGREGAR UNA CUENTA DE USUARIO AHORA? ☺");
           si.setVisible(true);
         no.setVisible(true);
         admin.setEnabled(false);
         vendedor.setEnabled(false);
         
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        admin = new javax.swing.JButton();
        si = new javax.swing.JButton();
        no = new javax.swing.JButton();
        vendedor = new javax.swing.JButton();
        lausuario = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox<>();
        usuarioincorrecto = new javax.swing.JLabel();
        contraseña = new javax.swing.JTextField();
        lacontraseña = new javax.swing.JLabel();
        contraseñaincorrecta = new javax.swing.JLabel();
        acceder = new javax.swing.JButton();
        accedervendedor = new javax.swing.JButton();
        vendedorpassword = new javax.swing.JTextField();
        labelvendedor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        labe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("HP Simplified", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SOFTWARE PARA EL MANEJO DE INVENTARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 463, 55));

        admin.setBackground(null);
        admin.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        admin.setForeground(new java.awt.Color(0, 0, 0));
        admin.setText("Ingresar como Administrador");
        admin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel1.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 284, 40));

        si.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        si.setForeground(new java.awt.Color(255, 255, 255));
        si.setText("SI");
        si.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        si.setOpaque(false);
        jPanel1.add(si, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        no.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        no.setForeground(new java.awt.Color(255, 255, 255));
        no.setText("NO");
        no.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        no.setOpaque(false);
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        vendedor.setBackground(null);
        vendedor.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        vendedor.setForeground(new java.awt.Color(0, 0, 0));
        vendedor.setText("Ingresar como Vendedor");
        vendedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendedorActionPerformed(evt);
            }
        });
        jPanel1.add(vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 285, 40));

        lausuario.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        lausuario.setForeground(new java.awt.Color(255, 255, 255));
        lausuario.setText("Ingrese su Usuario");
        jPanel1.add(lausuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 119, -1));

        usuario.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 124, -1));

        combo.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedores" }));
        combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboMouseEntered(evt);
            }
        });
        combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comboKeyTyped(evt);
            }
        });
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 190, 30));

        usuarioincorrecto.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        usuarioincorrecto.setForeground(new java.awt.Color(255, 255, 255));
        usuarioincorrecto.setText("Usuario Incorrecto");
        jPanel1.add(usuarioincorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 120, -1));

        contraseña.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jPanel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 124, -1));

        lacontraseña.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        lacontraseña.setForeground(new java.awt.Color(255, 255, 255));
        lacontraseña.setText("Ingrese su Contraseña");
        jPanel1.add(lacontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 119, -1));

        contraseñaincorrecta.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        contraseñaincorrecta.setForeground(new java.awt.Color(255, 255, 255));
        contraseñaincorrecta.setText("Contraseña Incorrecta");
        jPanel1.add(contraseñaincorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 130, -1));

        acceder.setBackground(null);
        acceder.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        acceder.setForeground(new java.awt.Color(0, 0, 0));
        acceder.setText("Acceder");
        acceder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accederActionPerformed(evt);
            }
        });
        jPanel1.add(acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 260, 20));

        accedervendedor.setBackground(null);
        accedervendedor.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        accedervendedor.setForeground(new java.awt.Color(0, 0, 0));
        accedervendedor.setText("Acceder");
        accedervendedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        accedervendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accedervendedorActionPerformed(evt);
            }
        });
        jPanel1.add(accedervendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 190, 20));

        vendedorpassword.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        vendedorpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendedorpasswordMouseClicked(evt);
            }
        });
        jPanel1.add(vendedorpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 190, 20));

        labelvendedor.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        labelvendedor.setForeground(new java.awt.Color(255, 255, 255));
        labelvendedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelvendedor.setText("Ingrese la contraseña");
        jPanel1.add(labelvendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 190, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMG_31052022_085355_(170_x_160_píxel).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 140));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 450, 10));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labe, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(labe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
      admin.setEnabled(true);
       vendedor.setEnabled(true);
         
         labe.setVisible(false);
          si.setVisible(false);
         no.setVisible(false);
         
    }//GEN-LAST:event_noActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        noverbotones();
         veropcionesdeadmin();
         admin.setEnabled(false);
         vendedor.setEnabled(true);
    }//GEN-LAST:event_adminActionPerformed

    private void vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendedorActionPerformed
        // TODO add your handling code here:
        verbotones();
        noveropcionesdeadmin();
        combo.setVisible(true);
       vendedor.setEnabled(false);
        admin.setEnabled(true);
        noverincorrecto();
    }//GEN-LAST:event_vendedorActionPerformed
public void versino(){
    si.setVisible(true);
    no.setVisible(true);
}
public void noversino(){
    si.setVisible(false);
    no.setVisible(false);
}
    
    
    
    String u,c;


    private void accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accederActionPerformed
     
        String usu=String.valueOf(usuario.getText());
       
       String cont=String.valueOf(contraseña.getText());
        try {
            conexion();
            Statement s=con.createStatement();
            ResultSet r=s.executeQuery("SELECT * FROM credenciales where credencial = 'Administrador ' ");
            while(r.next()){
               u=r.getString("usuario");
             c=r.getString("contraseña");  
            }
            
            
            if(u.equals(usu) && c.equals(cont)){
                JOptionPane.showMessageDialog(null, "Abrimos ventana de administrador");
                Panel22 padmin = new Panel22();
                padmin.setVisible(true);
                this.dispose();
                noverincorrecto();
            }else if (u.equals(usu) && c!=cont){
              contraseñaincorrecta.setVisible(true);
              usuarioincorrecto.setVisible(false);
            }
            else if (c.equals(cont) && u!=usu){
              usuarioincorrecto.setVisible(true);
              contraseñaincorrecta.setVisible(false);
            }else{
                verincorrecto();
            }
            vendedor.setEnabled(true);
             noversino();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Access.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Access.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_accederActionPerformed

    private void comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboMouseClicked

    private void comboKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboKeyTyped

    private void comboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboMouseEntered
String p ,us;
    private void accedervendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accedervendedorActionPerformed
        // TODO add your handling code here:
        if(combo.getSelectedItem().equals("Vendedores")){
            vendedorpassword.setText("Escoje una cuenta");
            vendedorpassword.setBackground(Color.white);
            vendedorpassword.setForeground(Color.red);
            
        }
        if (combo.getSelectedItem()!="Vendedores" ) {
        String passw = vendedorpassword.getText();
        String vendedor  = combo.getSelectedItem().toString();
        
            try {
                conexion();
                Statement s=con.createStatement();
                String sql="Select * from credenciales where usuario = '"+vendedor+"'";
                ResultSet r=s.executeQuery(sql);
                while(r.next()){
                  p=r.getString("contraseña");
                  us=r.getString("usuario");
                    
                }
                
                if(passw.equals(p) && us.equals(vendedor) ){
                    JOptionPane.showMessageDialog(null, "Abrimos ventana de vendedor");
                    
                    PV pvv = new PV();
                    pvv.setVisible(true);
                    this.dispose();
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Access.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Access.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_accedervendedorActionPerformed

    private void vendedorpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendedorpasswordMouseClicked
        // TODO add your handling code here:
        vendedorpassword.setText("");
    }//GEN-LAST:event_vendedorpasswordMouseClicked

    
    public void veropcionesdeadmin(){
        combo.setVisible(false);
        lausuario.setVisible(true);
         lacontraseña.setVisible(true);
         usuario.setVisible(true);
         contraseña.setVisible(true);
         acceder.setVisible(true);
         
    }
    public void noveropcionesdeadmin(){
        lausuario.setVisible(false);
         lacontraseña.setVisible(false);
         usuario.setVisible(false);
         contraseña.setVisible(false);
         acceder.setVisible(false);
    }
    
    public void verincorrecto(){
        usuarioincorrecto.setVisible(true);
        contraseñaincorrecta.setVisible(true);
    }
     public void noverincorrecto(){
        usuarioincorrecto.setVisible(false);
        contraseñaincorrecta.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Access().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Access.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Access.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceder;
    private javax.swing.JButton accedervendedor;
    private javax.swing.JButton admin;
    public javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField contraseña;
    private javax.swing.JLabel contraseñaincorrecta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labe;
    private javax.swing.JLabel labelvendedor;
    private javax.swing.JLabel lacontraseña;
    private javax.swing.JLabel lausuario;
    private javax.swing.JButton no;
    private javax.swing.JButton si;
    private javax.swing.JTextField usuario;
    private javax.swing.JLabel usuarioincorrecto;
    private javax.swing.JButton vendedor;
    private javax.swing.JTextField vendedorpassword;
    // End of variables declaration//GEN-END:variables
}
