/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectotienda;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author chris
 */
public class EDRCategorias extends javax.swing.JPanel {

    /**
     * Creates new form EDRCategorias
     */
    public EDRCategorias() {
        initComponents();
        consultar();
        Grafica();
    }
    Conexion con1 = new Conexion();
    Connection conet;
    DefaultTableModel model;
    Statement st;
    ResultSet rs;
    int idc;
    
    //INICIO
    void consultar(){
    String sql = "SELECT * FROM categoria";
        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            
            //Objecto con numero de columnas de la tabla:
            Object cat[] = new Object[10];
            model = (DefaultTableModel) jTable1.getModel();
            while (rs.next()) {                
                cat[0]= rs.getString("id_categorias");
                cat[1]= rs.getString("nombre");
                cat[2]= rs.getString("descripcion");
                
                
                model.addRow(cat);
            }
            jTable1.setModel(model);
            
        } catch (Exception e) {
        }
        
        if (jTable1.getRowCount()>0) {
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                
            }
        }
    }
    
    //GRAFICA DE LA TABLA DE "CATEGORIA"
    void Grafica(){
    double uno=8.33,dos=8.33,tres=8.33,cuatro=8.33,cinco=8.33,seis=8.33,siete=8.33,ocho=8.33,nueve=8.33,diez=8.33,once=8.33,doce=8.33;
    
    DefaultPieDataset datos = new DefaultPieDataset();
    //Asignacion de valores
    datos.setValue("Abarrotes  "+uno+"%", 8.33);
    datos.setValue("Auto medicacion  "+dos+"%", dos);
    datos.setValue("Bebidas Alcoholicas  "+tres+"%", tres);
    
    datos.setValue("Bebidas  "+cuatro+"%", cuatro);
    datos.setValue("Botanas  "+cinco+"%", cinco);
    datos.setValue("Cafeteria y dulceria  "+seis+"%", seis);
    
    datos.setValue("Higiene personal  "+siete+"%", siete);
    datos.setValue("Helados  "+ocho+"%", ocho);
    datos.setValue("Harinas y pan  "+nueve+"%", nueve);
    
    datos.setValue("Lacteos  "+diez+"%", diez);
    datos.setValue("Productos enlatados  "+once+"%", once);
    datos.setValue("Productos de Limpieza  "+doce+"%", doce);
    
    JFreeChart grafico = ChartFactory.createPieChart(
    "Categorias Total Maxima Aceptable de productos",
    datos,
    true,
    true,
    false
    );
    
    ChartPanel panel = new ChartPanel(grafico);
    panel.setMouseWheelEnabled(true);
    panel.setPreferredSize(new Dimension (497, 573));
    
    graficoPastel.setLayout(new BorderLayout());
    graficoPastel.add(panel, BorderLayout.NORTH);
    //pack();
    repaint();
    }
    
    //--------------------------------------------------------------------------
    void InversionProductos(){
    double uno=8.33,dos=8.33,tres=8.33,cuatro=8.33,cinco=8.33,seis=8.33,siete=8.33,ocho=8.33,nueve=8.33,diez=8.33,once=8.33,doce=8.33;
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        graficoPastel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new rojeru_san.complementos.RSTableMetro();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setMaximumSize(new java.awt.Dimension(500, 500));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("TABLA DE CATEGORIA");
        content.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 32, -1, -1));

        graficoPastel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout graficoPastelLayout = new javax.swing.GroupLayout(graficoPastel);
        graficoPastel.setLayout(graficoPastelLayout);
        graficoPastelLayout.setHorizontalGroup(
            graficoPastelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        graficoPastelLayout.setVerticalGroup(
            graficoPastelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        content.add(graficoPastel, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 55, 550, 590));

        jLabel3.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Inversion realizada en la compra de productos:");
        content.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        content.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 316, 540, -1));

        jTable1.setBackground(new java.awt.Color(255, 51, 0));
        jTable1.setForeground(new java.awt.Color(255, 51, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Categorias", "Nombre", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColorBackgoundHead(new java.awt.Color(255, 51, 0));
        jScrollPane2.setViewportView(jTable1);

        content.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 540, 230));

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JPanel graficoPastel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private rojeru_san.complementos.RSTableMetro jTable1;
    // End of variables declaration//GEN-END:variables
}
