/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectotienda;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chris
 */
public class Ingresar extends javax.swing.JPanel {

    /**
     * Creates new form Ingresar
     */
    public Ingresar() {
        initComponents();
       
        limpiar();
    consultar();
    }
    
    
    void ingresar(){
     Conexion con1 = new Conexion();
     Connection conet;
     DefaultTableModel modelo;
     Statement stm;
     ResultSet rs;
     int idc;

    
    String id_delproducto = jTextField6.getText();
    String nombre = jTextField1.getText();
    float precio = Float.parseFloat(jTextField2.getText());
    int stock = Integer.parseInt(jTextField3.getText());
    String id_proveedor = jTextField4.getText();
    String categoria = String.valueOf(jComboBox3.getSelectedItem());
    String caducidad = jTextField5.getText();
    try {
        if(nombre.equals("")){
          JOptionPane.showMessageDialog(null,"No ingrese campos vacios");
        }else{
        String sql = "INSERT INTO `productos`(`id_producto`, `nombre`, `precio`, `stock`, `id_proveedor`, `id_categoria`, `caducidad`) VALUES ('"+id_delproducto+"','"+nombre+"','"+precio+"','"+stock+"','"+id_proveedor+"','"+categoria+"','"+caducidad+"')";
        conet = con1.getConnection();
        stm = conet.createStatement();
        stm.executeUpdate(sql);
        JOptionPane.showMessageDialog(null, "HAZ INGRESADO UN NUEVO PRODUCTO");
         limpiar();
         consultar();
        }
        }catch (Exception e) {
        }
    }
    
Conexion con1  = new Conexion();
Connection conet;
DefaultTableModel modelo;
Statement stm;
ResultSet rs;
int idc;
   
    void consultar(){
    String sql = "Select*from productos";
        try {
        conet = con1.getConnection();
        stm = conet.createStatement();
        rs = stm.executeQuery(sql);
        Object[] ob = new Object[8];
        modelo = (DefaultTableModel) jTable2.getModel();
        while (rs.next()) {                
                ob[0]= rs.getString("id_producto");
                ob[1]= rs.getString("nombre");
                ob[2]= rs.getString("precio");
                
                ob[3]= rs.getString("stock");
                ob[4]= rs.getString("id_proveedor");
                ob[5]= rs.getString("id_categoria");
                ob[6]= rs.getString("caducidad");
        
        modelo.addRow(ob);
        }
        jTable2.setModel(modelo);
        } catch (Exception e) {
        }
    }
    
    void limpiar(){
       
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            modelo.removeRow(i);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setMaximumSize(new java.awt.Dimension(500, 500));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("id_del_producto");
        content.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bienvenido al panel:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ingresar");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        content.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1157, 0, 190, 660));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel5.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AGREGAR");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        content.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 44, 240, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_producto", "nombre", "precio", "stock", "id_proveedor", "id_categoria", "caducidad"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        content.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 469, 480));

        jLabel11.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("nombre");
        content.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jLabel12.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("precio");
        content.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        jLabel13.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("stock");
        content.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        jLabel14.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("id_proveedor");
        content.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jLabel15.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("id_categoria");
        content.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jLabel16.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("caducidad");
        content.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));
        content.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 90, -1));
        content.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 90, -1));
        content.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, -1));
        content.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 90, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Lcts", "Hlds", "Cfdc", "Psla", "Hgpl", "Bdash", "Btns", "Pdes", "Hrpn", "Atmn", "Abrs", "Bdas" }));
        content.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 90, -1));
        content.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 90, -1));
        content.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
       ingresar();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void sp (JPanel p){
    p.setSize(500,500);
    p.setLocation(0,0);
    
    content.removeAll();
    content.add(p, BorderLayout.CENTER);
    content.revalidate();
    content.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
